# Generated by Django 5.2.4 on 2025-07-14 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("path", models.CharField(max_length=200)),
            ],
        ),
    ]
